tmdb:
  baseUri: https://api.themoviedb.org/3/
  apiKey: ec111e07c4ae78be4beb39617994c039

slack:
  token: ${SLACK_TOKEN}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
server:
  port: 8888

logging:
  level:
    com.pse: DEBUG
    com.slack.socket_mode.SocketModeClient: INFO